SVE: Geneal Fixes
agilbert1412/StardewArchipelago pull request #15
Opened 2023-12-13 21:57 UTC by Witchybun

Does the following:
- Forces Gunther to show up immediately (hopefully).
- Fix Marlon shop recipes.
- ""Fixes"" Claire and Martin schedules.  Admittedly half baked, what it does is on day started, fix their schedule if they received the second movie theater; however the first day this occurs it won't be fixed.  Why I don't know.  Even utilizing onSaveLoaded is not enough.  So for now accept day one screwup from them.

2023-12-13 22:42 UTC, Witchybun commented
I also added a thing so magic just unlocks if you get a spell aren't I nice?

2023-12-13 23:33 UTC, agilbert1412 requested changes

2023-12-13 23:33 UTC, agilbert1412 commented on StardewArchipelago/Items/Unlocks/MagicUnlockManager.cs
> +                if (farmer.eventsSeen.Contains(90001))
If you have already seen 90001, see it again? what?

2023-12-13 23:33 UTC, agilbert1412 commented on StardewArchipelago/Locations/CodeInjections/Modded/SVE/SVECutsceneInjections.cs
> +        public static void ChangeScheduleForMovie()
Why is this static?

2023-12-13 23:33 UTC, agilbert1412 commented on StardewArchipelago/Locations/CodeInjections/Modded/SVE/SVECutsceneInjections.cs
> +            if (_archipelago.GetReceivedItemCount("Progressive Movie Theater") >= 2)
invert if, and also merge with previous if

2023-12-13 23:33 UTC, agilbert1412 commented on StardewArchipelago/Locations/CodeInjections/Modded/SVE/SVECutsceneInjections.cs
> +            if (_archipelago.GetReceivedItemCount("Progressive Movie Theater") >= 2)
Use movie theater string constant

2023-12-13 23:33 UTC, agilbert1412 commented on StardewArchipelago/Locations/CodeInjections/Modded/SVE/SVECutsceneInjections.cs
> +                foreach(var name in charactersToModify)
Why not loop over the entries of "characterToSchedule", since it is these characters anyway?

2023-12-13 23:33 UTC, agilbert1412 commented on StardewArchipelago/Locations/CodeInjections/Modded/SVE/SVECutsceneInjections.cs
> +                    foreach (KeyValuePair<string, string> day in schedules)
var

2023-12-13 23:33 UTC, agilbert1412 commented on StardewArchipelago/Locations/CodeInjections/Modded/SVE/SVECutsceneInjections.cs
> +                        if (characterToSchedule[name].Keys.Contains(day.Key))
dictionaries have a `ContainsKey()` method

2023-12-13 23:33 UTC, agilbert1412 commented on StardewArchipelago/Locations/CodeInjections/Modded/SVE/SVECutsceneInjections.cs
> +                            schedules[day.Key] = characterToSchedule[name][day.Key];
This is vulnerable to race conditions. You should not be modifying a dictionary while iterating on it

2023-12-13 23:33 UTC, agilbert1412 commented on StardewArchipelago/Locations/CodeInjections/Modded/SVE/SVECutsceneInjections.cs
> +                        if (characterToSchedule[name].Keys.Contains(day.Key))
If you are only interested in the days that are present in your custom schedule, why not loop over that one, instead of the full schedule?

2023-12-13 23:33 UTC, agilbert1412 commented on StardewArchipelago/ModEntry.cs
> +            SVECutsceneInjections.ChangeScheduleForMovie();
Why is this static?

2023-12-13 23:33 UTC, agilbert1412 commented on StardewArchipelago/ModEntry.cs
> +                if (_archipelago.SlotData.Mods.HasMod(ModNames.SVE) && !Game1.player.mailReceived.Contains("GuntherUnlocked"))
I don't want arbitrary mod code snippets in here. At **most**, one line for "DoModInitializationOnGameLoad()" and have the actual content in there.

Speaking of, I am just now noticing this weird "OnWarp" event being registered, then executing code that should not happen at each warp. It should probably also be moved out. And most important, not be static arrghh

2023-12-14 02:07 UTC, Witchybun commented on StardewArchipelago/Locations/CodeInjections/Modded/SVE/SVECutsceneInjections.cs
> +        public static void ChangeScheduleForMovie()
Its in a static class.

2023-12-14 02:14 UTC, Witchybun commented on StardewArchipelago/Locations/CodeInjections/Modded/SVE/SVECutsceneInjections.cs
> +        public static void ChangeScheduleForMovie()
Nevermind me dum

2023-12-14 17:21 UTC, agilbert1412 requested changes

2023-12-14 17:21 UTC, agilbert1412 commented on StardewArchipelago/Locations/CodeInjections/Modded/CallableModData.cs
> +        public void Initialize(IMonitor monitor, ArchipelagoClient archipelago)
Why isn't this method a constructor now?

2023-12-16 07:30 UTC, Witchybun commented
There was an error where no club weapons were in tier 3.  I decided to just write the uniform distribution method.

2023-12-16 15:01 UTC, agilbert1412 approved these changes

2023-12-16 15:01 UTC, merged