Content Patcher Support
agilbert1412/StardewArchipelago pull request #18
Opened 2023-12-19 06:54 UTC by Witchybun

Removes a lot of the code dealing with modifying events and schedules.  Instead, these will be handled by content patchers for a more consistent experience.  These can be obtained from here:

https://github.com/Witchybun/SDV-Randomizer-Content-Patcher

The supported mods documentation now includes a link to this, the mods that are modified, and why.

2023-12-19 11:42 UTC, Witchybun commented
Went and shifted the weapon weights.  A lot of the weapons are super low level so the 1 , 2, 3, 3, 2, 1 split was letting too many weak weapons to be mid-way making a lot of the tiers kinda useless.  Doing this should help with that.

2023-12-20 01:59 UTC, agilbert1412 requested changes

2023-12-20 01:59 UTC, agilbert1412 commented on StardewArchipelago/Archipelago/ArchipelagoClient.cs
> +            if (!SlotData.Mods.IsPatcherStateCorrect(_modHelper, out errorMessage))
can you put that in the `#if RELEASE` block, so that we don't have to deal with it when debugging, like the mod state?

2023-12-20 01:59 UTC, agilbert1412 commented on Documentation/Supported Mods.md
> +In addition, a [Content Patcher mod](https://github.com/Witchybun/SDV-Randomizer-Content-Patcher) may be required for the mod to properly function alongside your game.  Include these alongside Starde
I would suggest making this a link to your releases page within the github, for ease of use

2023-12-20 01:59 UTC, agilbert1412 commented on StardewArchipelago/Archipelago/ModsManager.cs
> +                var contentName = ModVersions.CPVersions[modName].Keys.First();
Assuming that you made these a dictionary to account for possible multiple dependencies in the future, why only check the first? Why not check all here?

2023-12-20 01:59 UTC, agilbert1412 commented on StardewArchipelago/GameModifications/CodeInjections/TheaterInjections.cs
> +                    if (!Game1.player.mailReceived.Contains(string.Join("ap",ABANDONED_JOJA_MART)))
Why not send this letter when receiving the actual movie theater, instead of here?

2023-12-20 01:59 UTC, agilbert1412 commented on StardewArchipelago/Archipelago/ModsManager.cs
> +using System.Reflection.Metadata.Ecma335;
Okay what is this monstrosity?

2023-12-20 01:59 UTC, agilbert1412 commented on StardewArchipelago/Archipelago/ModsManager.cs
> +using Microsoft.VisualBasic;
Also Visual Basic? What?

2023-12-20 01:59 UTC, agilbert1412 commented on StardewArchipelago/Locations/CodeInjections/Vanilla/ShippingInjections.cs
> +                    name = name.Replace("Woooden", "Wooden");
You don't need an if. Running string.Replace(str1, str2) will simply do nothing if str1 is not present

2023-12-20 01:59 UTC, agilbert1412 commented on StardewArchipelago/ModEntry.cs
> +            foreach (var eventID in deprecatedEvents)
use variable deconstruction iteration

2023-12-20 05:46 UTC, agilbert1412 approved these changes

2023-12-20 05:46 UTC, merged