Fix Gus' shop when he's at the island
agilbert1412/StardewArchipelago pull request #21
Opened 2023-12-21 19:54 UTC by Witchybun

Self-explanatory.

2023-12-22 17:18 UTC, agilbert1412 requested changes

2023-12-22 17:18 UTC, agilbert1412 commented on StardewArchipelago/Locations/CodeInjections/Modded/MagicModInjections.cs
> +        public static void Update_ReplaceMarlonShopChecks_Postfix(ShopMenu __instance, GameTime time)
Please add the signature of the function you're patching above the patch like in other places

2023-12-22 17:18 UTC, agilbert1412 commented on StardewArchipelago/Locations/CodeInjections/Modded/SVE/SVEShopInjections.cs
> +            { new ShopIdentification("FarmHouse", "Marlon"), new[] { new PricedItem("Frog Legs", 2000), new PricedItem("Mushroom Berry Rice", 1500) } },
I don't think we should sell these from the phone?

2023-12-22 17:18 UTC, agilbert1412 commented on StardewArchipelago/Locations/CodeInjections/Modded/MagicModInjections.cs
> +            { new ShopIdentification("FarmHouse", "Marlon"), new[] { new PricedItem("Magic Elixir", 3000), new PricedItem("Travel Charm", 250) } },
I don't think we should sell these from the phone?

2023-12-22 17:18 UTC, agilbert1412 commented
You can't say "Self Explanatory" as a description when the PR contains a bunch of Marlon-related changes that are not in the title lmao

2023-12-24 08:01 UTC, Witchybun commented
I renamed it due to the comment; it was named before I noticed Marlon with the same problem.  That's it.

2023-12-24 11:42 UTC, Witchybun commented
I think I will just clear my workspace.  Have fun with this lmao

2023-12-25 18:30 UTC, Witchybun commented
I'll clean this up and just send it later.

2023-12-25 18:30 UTC, closed without merging