Add Null Type Exceptions
agilbert1412/StardewArchipelago pull request #80
Opened 2024-07-23 23:56 UTC by RubyyaCode

2024-07-24 04:01 UTC, agilbert1412 commented
Is this not just a duplicate of https://github.com/agilbert1412/StardewArchipelago/pull/79 ?

2024-07-24 13:03 UTC, RubyyaCode commented
This one is hopefully pushed from Git, as opposed to me directly editing the code on Github.

2024-07-24 13:12 UTC, agilbert1412 commented
Oh, I see. Alright then, can you close #79 ?

2024-07-24 13:13 UTC, agilbert1412 requested changes
Copied the comment from #79

2024-07-24 13:13 UTC, agilbert1412 commented on StardewArchipelago/Archipelago/Gifting/GiftGenerator.cs
> +            var type = objectInfo.Type ?? string.Empty;
This doesn't work in addition to line 147, it needs to be instead. As it currently is, I'm pretty sure it won't even build.

2025-01-01 01:53 UTC, agilbert1412 commented
No updates in over 5 months, closing. If you want to reopen it, feel free

2025-01-01 01:53 UTC, closed without merging